# Generated by Django 5.0.14 on 2025-11-03 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0002_brand_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale', models.IntegerField(default=0)),
                ('company', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, default=list, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
