# Generated by Django 5.0.14 on 2025-10-17 08:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('id_blog', 'id_user')},
        ),
    ]
