# Generated by Django 5.0.14 on 2025-10-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='avatar_user',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
